### ISSUE TITLE
Transformer上的数据网站无法加载

### ISSUE THREAD

**Issue by zhangyandsg** [candle-org/step_into_llm#38]
Error while fetching file http://www.quest.dcs.shef.ac.uk/wmt16_files_mmt/training.tar.gz. Dataset fetching aborted.
Error: HTTP Error 502: Bad Gateway

**Comment by lvyufeng** [comment]
这个网站好像挂了，用这个仓里的https://openi.pcl.ac.cn/lvyufeng/multi30k
